spring:
  application:
    name: zuul-service

server:
  port: 8762

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    allow-redirects: true

zuul:
  ignoredServices: '*'
  routes:
    message-service:
      serviceId: message-service
      path: /message-service/**
      url: "http://localhost:8100"
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials,Access-Control-Allow-Origin

    auth-service:
      serviceId: auth-service
      path: /auth-service/**
      url: "http://localhost:8200"
      sensitiveHeaders: Cookie,Set-Cookie,Access-Control-Allow-Credentials,Access-Control-Allow-Origin

  host:
    connect-timeout-millis: 86400000
    socket-timeout-millis: 86400000
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin


ribbon:
  eureka:
    enabled: false



management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        max-age: 86400000